import { capturePage } from "../src/engine/crawl";
import fs from "node:fs";
const url = process.argv[2] ?? "https://tastelabs.com";
const t = Date.now();
const c = await capturePage(url);
const s = c.signals;
console.log("via", c.via, "ms", Date.now() - t, "final", c.finalUrl, "docH", s.docHeight);
console.log("title", s.title);
console.log("colors", s.colors.slice(0, 10).map((x) => `${x.hex}@${x.alpha} w${x.weight.toFixed(1)}`).join(" "));
console.log("text", s.textStyles.slice(0, 8).map((x) => `${x.tag}:${x.family.slice(0,30)} ${x.size}/${x.weight}`).join(" | "));
console.log("fonts", s.fontFaces.map((f) => f.family).join(","), "loaded", s.loadedFonts.join(","));
console.log("buttons", s.buttons.map((b) => `${b.text}[${b.css.backgroundColor}|hover:${b.hover?.backgroundColor}]`).join(" ; "));
console.log("nav", JSON.stringify(s.nav));
console.log("logo", s.logo?.kind, s.logo?.src ?? s.logo?.svg?.slice(0, 80));
console.log("sections", s.sections.map((x) => `${x.bg} ${x.headline.slice(0,40)}`).join(" || "));
console.log("kf", s.keyframes.map((k) => k.name).join(","), "mq", s.mediaQueries.slice(0,5).join(" ; "));
console.log("icons", s.icons.length, "media", s.media.length, "shadows", s.shadows.length, "css bytes", c.css.length, "html", c.html.length, "shot", c.screenshot?.length);
fs.writeFileSync("/tmp/onbrand-shot.jpg", c.screenshot!);
process.exit(0);
