import { OnBrand } from "../packages/sdk/src/index.ts";
const ob = new OnBrand({ apiKey: process.env.K, baseUrl: process.env.BASE ?? "http://localhost:3100" });
console.log("me", (await ob.me()).credits);
const s = await ob.search({ query: "luxury editorial skincare", top_k: 3, filters: { industry: "beauty" } });
console.log("search", s.results.map((r) => `${r.brand_name} (${r.match ?? r.badge})`));
const e = await ob.extract({ url: "https://tastelabs.com/", wait: true });
console.log("extract", e.id, e.status, e.cache_hit);
const r = await ob.result(e.id, { sections: ["colors"] });
console.log("result keys", Object.keys(r?.brand ?? {}));
console.log("brief", (await ob.brief(e.id)).slice(0, 80).replace(/\n/g, " "));
console.log("enhance", (await ob.enhance(e.id, "a careers page")).slice(0, 80).replace(/\n/g, " "));
console.log("similar", (await ob.similar(e.id, 3)).results.map((x) => x.brand_name));
console.log("download", (await ob.download(e.id)).files.map((f) => f.path).slice(0, 4));
console.log("history", (await ob.searchHistory({ limit: 2 })).total);
